# Generated by Django 5.2.1 on 2025-05-30 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Um breve título para o reporte.', max_length=255)),
                ('descricao', models.TextField(help_text='Descreva detalhadamente o motivo do reporte.')),
                ('imagem_evidencia', models.ImageField(blank=True, null=True, upload_to='reportes_evidencias/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('resolvido_aprovado', 'Resolvido (Ação Tomada)'), ('resolvido_rejeitado', 'Resolvido (Rejeitado)'), ('arquivado', 'Arquivado')], default='aberto', max_length=20)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas do administrador sobre este reporte.', null=True)),
                ('data_ultima_atualizacao_admin', models.DateTimeField(auto_now=True)),
                ('produto_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_sobre_produto', to='marketplace.produto')),
                ('usuario_alvo_reporte', models.ForeignKey(blank=True, help_text='Usuário que está sendo reportado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_recebidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
