# Generated by Django 5.2.1 on 2025-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_avaliacao_cliente_alter_pedido_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcomprador',
            name='desejos',
            field=models.ManyToManyField(blank=True, related_name='compradores_desejam', to='marketplace.produto'),
        ),
    ]
