# Generated by Django 5.2.1 on 2025-06-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category'),
        ),
    ]
