# Generated by Django 5.2.1 on 2025-06-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_produto_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
