# Generated by Django 5.2.1 on 2025-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_delete_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
