# Generated by Django 5.2.1 on 2025-06-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_produto_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
    ]
